import Link from 'next/link';
import { ArrowRight, PenTool, TrendingUp, ShieldCheck } from 'lucide-react';

export default function Home() {
  return (
    <main style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column' }}>
      <nav style={{ padding: '24px 5%', display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid var(--border-color)' }}>
        <h2 className="gradient-text" style={{ fontSize: '1.8rem', margin: 0 }}>Thoughtry</h2>
        <div style={{ display: 'flex', gap: '16px' }}>
          <Link href="/login"><button className="btn-secondary">Login</button></Link>
          <Link href="/register"><button className="btn-primary">Start Writing</button></Link>
        </div>
      </nav>

      <section style={{ flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', textAlign: 'center', padding: '60px 5%' }}>
        <h1 style={{ fontSize: '4rem', maxWidth: '800px', marginBottom: '24px' }}>
          Your Voice. Your Subdomain. <br/>
          <span className="gradient-text">Your Revenue.</span>
        </h1>
        <p style={{ fontSize: '1.2rem', color: 'var(--text-muted)', maxWidth: '600px', marginBottom: '40px' }}>
          Join Thoughtry to get your own personalized <b>.thoughtry.blog</b> subdomain. Publish your articles with a beautiful rich-text editor and earn money from day one through our integrated PopAds revenue split.
        </p>
        <Link href="/register">
          <button className="btn-primary" style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '1.1rem', padding: '16px 32px' }}>
            Claim Your Subdomain <ArrowRight size={20} />
          </button>
        </Link>
      </section>

      <section style={{ padding: '80px 5%', background: 'rgba(255,255,255,0.02)' }}>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '32px', maxWidth: '1200px', margin: '0 auto' }}>
          <div className="glass-panel" style={{ padding: '32px', textAlign: 'center' }}>
            <PenTool size={40} color="var(--primary)" style={{ marginBottom: '16px' }} />
            <h3 style={{ fontSize: '1.5rem', marginBottom: '12px' }}>Rich Editor</h3>
            <p style={{ color: 'var(--text-muted)' }}>Write beautiful articles using our advanced editor with custom fonts, image uploads, and clean formatting.</p>
          </div>
          <div className="glass-panel" style={{ padding: '32px', textAlign: 'center' }}>
            <TrendingUp size={40} color="var(--accent)" style={{ marginBottom: '16px' }} />
            <h3 style={{ fontSize: '1.5rem', marginBottom: '12px' }}>70% Revenue Share</h3>
            <p style={{ color: 'var(--text-muted)' }}>You keep 70% of the ad revenue generated by your blog. Withdrawals are processed monthly with a low $10 minimum.</p>
          </div>
          <div className="glass-panel" style={{ padding: '32px', textAlign: 'center' }}>
            <ShieldCheck size={40} color="var(--secondary)" style={{ marginBottom: '16px' }} />
            <h3 style={{ fontSize: '1.5rem', marginBottom: '12px' }}>SEO Optimized</h3>
            <p style={{ color: 'var(--text-muted)' }}>Built with Next.js, your blog is lightning fast and fully optimized for search engines right out of the box.</p>
          </div>
        </div>
      </section>
    </main>
  );
}
